language: python

cache:
    apt
    pip

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

before_install:
  - sudo add-apt-repository -y ppa:shnatsel/dnscrypt
  - sudo apt-get update
  - pip install -q --use-mirrors nose pyzmq gevent

script: 
  - python setup.py test

